# NumPy Hands-On Practice
## From Python Lists to Numerical Computing
## Project Title: Weather Temperature Analysis with NumPy
## Author: Ismaila Aminu Ainoko 

### Project Introduction

#### This project uses NumPy to analyze temperature data from three locations: Lagos, Abuja, and Ibadan. The project focuses on using NumPy arrays to store temperature data, perform numerical calculations, and compare temperatures between the different locations.

#### The goal of this project is to practice basic NumPy skills and understand how NumPy can be used to analyze numerical data efficiently.

In [53]:
## Task 1: Import Numpy
import numpy as np  
## it runs without an error that shows numpy is instal

## Task 2: Create Your Array
## Convert the temperatures list into a NumPy array
temperatures = [27.5, 29,  28.5]
temperatures_array = np.array(temperatures)
print(temperatures_array)

## Task 3: Inspect the Data Type
print(temperatures_array.dtype)

## Task 4 — Create a 2D Array
## Now imagine three weather stations recorded temperatures over two days:
weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]

print(weather_data)


[27.5 29.  28.5]
float64
[[27.5, 28.0, 29.5], [28.0, 29.0, 30.0]]


## HANDS-ON 2
### Python Lists vs NumPy Arrays


In [64]:
## The manager wants the combine list of sales from both staffs
## Task 1: Try It With Python Lists

sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

sales_timothy + sales_brenda

## Comments:
# 1. No, Python did not produce [15, 25, 35].
# 2. Python joined (concatenated) the two lists together.
# 3. This happened because + with Python lists means joining the lists, not adding corresponding elements.



[10, 15, 20, 5, 10, 15]

In [65]:
## Task 2: Convert Them to NumPy Arrays
sales_timothy_array = np.array(sales_timothy)
sales_brenda_array = np.array(sales_brenda)

sales_timothy_array + sales_brenda_array

array([15, 25, 35])

In [68]:
## Task 3: Compare the Results From the above task 1 and task 2 
# Comparison

# Python lists
# Result: [10, 15, 20, 5, 10, 15]

# NumPy arrays
# Result: [15, 25, 35]

# COMMENT 
# NumPy is useful because it allows us to perform mathematical
# NumPy allows us to simply use the + operator.

# Python lists concatenate (join) the two lists together instead of adding corresponding values.
# Python lists join the two lists together when we use +.


In [75]:
# Challenge 

#Calculate the combined sales for each day.

# Monday, Tuesday, Wednesday, Thursday, Friday
online_sales_array = np.array([100, 125, 150, 220, 190])
store_sales_array = np.array([115, 800, 340, 150, 220])

combined_sales = online_sales_array + store_sales_array

## calculates the difference between online and store sales.
differences = online_sales_array - store_sales_array

print("Combined Sales:", combined_sales)
print("Differences:", differences)



Combined Sales: [215 925 490 370 410]
Differences: [ -15 -675 -190   70  -30]


## HANDS-ON 3
## MINI PROJECT

### Project Title: Weather Temperature Analysis with NumPy


In [81]:
# i just created a python list 
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]
temperatures_array = np.array(temperatures)
print(temperatures_array)

[27.5 29.  30.5 28.  31.  32.5 30. ]


In [82]:
## Part 2 — Understand Your Array

# Question 1: Check the dimensions
print("Dimensions:", temperatures_array.ndim)

# Question 2: Check the shape
print("Shape:", temperatures_array.shape)

# Question 3: Check the data type
print("Data type:", temperatures_array.dtype)

# Question 4: Count the number of observations
print("Number of temperatures:", temperatures_array.size)

Dimensions: 1
Shape: (7,)
Data type: float64
Number of temperatures: 7


In [88]:
# Part 3 — Perform Numerical Operations
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
target_array = np.array(target)

# Calculate temperature difference 
temperature_differences = temperatures_array - target_array

# Increase every temperature by 2°C
temperature_increase = temperature_array + 2

print(target_array)
print(temperature_differences)
print(temperature_increase)





[28. 28. 29. 28. 30. 30. 29.]
[-0.5  1.   1.5  0.   1.   2.5  1. ]
[20.5 22.  27.  24.5 29. ]


# Business Question 1

The highest recorded temperature was 32.5°C, which occurred on Saturday.

# Business Question 2

The recorded temperature was above the target on:
- Tuesday
- Wednesday
- Friday
- Saturday
- Sunday

# Business Question 3

It tells the  whether monitoring team that the recorded temperature was above or below the target temperature. A positive difference means the recorded temperature was above the target, while a negative difference means it was below the target.

# Business Question 4

NumPy arrays are more convenient because they allow us to perform numerical calculations on all the temperature values at once. For example, we can add 2°C to every temperature without using a `for` loop.

# MINI PROJECT CHALLENGE
## Your task is to create NumPy arrays for all three locations.

In [108]:
# Imagine the weather station has three locations:
    
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

# to creatw a numpy array of the following list 
lagos_array = np.array(lagos)
abuja_array = np.array(abuja)
ibadan_array = np.array(ibadan)

print("Lagos:", lagos_array)
print("Abuja:", abuja_array)
print("Ibadan:", ibadan_array)

print()
# challenge 1: Which location recorded the highest temperature on each day?

highest_temperature = np.max([lagos_array, abuja_array, ibadan_array])
print("Lagos has the highest temperature record of", highest_temperature)

# Create a calculation that increases every recorded temperature by 1°C.
lagos_increased = lagos_array + 1
abuja_increased = abuja_array + 1
ibadan_increased = ibadan_array + 1

print()
print(lagos_increased)
print(abuja_increased)
print(ibadan_increased)

print()
# Create a calculation that compares Lagos temperatures with Abuja temperatures.
lagos_vs_abuja = lagos_array - abuja_array

print(lagos_vs_abuja)

### Challenge 4: Explain why NumPy becomes increasingly useful as the amount of numerical data grows.

NumPy becomes increasingly useful as the amount of numerical data grows because it allows us to perform 
calculations on many values at once. It is more convenient than using Python lists because we can add, subtract,
multiply, and divide arrays without using a `for` loop.

Lagos: [27.5 29.  30.5 28.  31. ]
Abuja: [25.  28.  29.5 30.  32. ]
Ibadan: [26.5 28.5 29.  27.5 30.5]

Lagos has the highest temperature record of 32.0

[28.5 30.  31.5 29.  32. ]
[26.  29.  30.5 31.  33. ]
[27.5 29.5 30.  28.5 31.5]

[ 2.5  1.   1.  -2.  -1. ]
